export const ADDED = 'todos/added'
export const TOGGLED = 'todos/toggled'
export const COLORSELECTED = 'todos/colorSelected'
export const DELETED = 'todos/deleted'
export const ALLCOMPLETED = 'todos/allCompleted'
export const CLEARCOMPLETED = 'todos/clearCompleted'
